import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const sb=createClient("https://jypfmjuesuezlmgfmrjq.supabase.co","sb_publishable_pAu0w7YvY4vk5sMect4LQw_-SG6ngls",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=id=>document.getElementById(id);let session,profile,leads=[];
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function when(v){return v?new Date(v).toLocaleString():"—"}function owner(){return ["owner","manager"].includes(profile.role)}
async function login(){$("message").textContent="Signing in…";let{error}=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});$("message").textContent=error?error.message:""}
async function reset(){let e=$("email").value.trim();if(!e)return $("message").textContent="Enter your email first.";let{error}=await sb.auth.resetPasswordForEmail(e,{redirectTo:location.href});$("message").textContent=error?error.message:"Password reset sent."}
async function enter(){let{data,error}=await sb.from("profiles").select("*").eq("id",session.user.id).single();if(error)throw error;profile=data;$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("userline").textContent=`${profile.full_name||profile.email} • ${profile.role}`;$("accountInfo").innerHTML=`<b>${esc(profile.full_name)}</b><br>${esc(profile.email)}<br><span class="pill">${profile.role}</span>`;renderNav();show(owner()?"owner":"employee")}
function renderNav(){let t=owner()?[['owner','⌂','Home'],['leads','📞','Leads'],['followups','🔁','Follow-Ups'],['team','⏱','Team Time'],['account','⚙','Account']]:[['employee','⌂','Home'],['time','⏱','Clock'],['account','⚙','Account']];$("nav").style.gridTemplateColumns=`repeat(${t.length},1fr)`;$("nav").innerHTML=t.map((x,i)=>`<button data-v="${x[0]}" class="${i?'':'active'}"><b>${x[1]}</b>${x[2]}</button>`).join('');$("nav").querySelectorAll('button').forEach(b=>b.onclick=()=>show(b.dataset.v))}
async function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===id));if(id==='owner')dashboard();if(id==='leads')loadLeads();if(id==='followups')loadFollowups();if(id==='time')loadTime();if(id==='employee')loadEmployee();if(id==='team')loadTeam()}
async function dashboard(){let now=new Date().toISOString();let[a,b,c]=await Promise.all([sb.from('leads').select('*',{count:'exact',head:true}).eq('status','new'),sb.from('leads').select('*',{count:'exact',head:true}).lte('next_follow_up_at',now),sb.from('time_entries').select('*',{count:'exact',head:true}).eq('status','open')]);$('newLeads').textContent=a.count||0;$('dueLeads').textContent=b.count||0;$('clocked').textContent=c.count||0;$('mission').innerHTML=`• ${a.count||0} new leads need contact.<br>• ${b.count||0} follow-ups are due.<br>• ${c.count||0} team members are clocked in.`}
function card(l,due=false){return `<div class="item"><div class="head"><h2>${esc((l.first_name+' '+l.last_name).trim()||'Unnamed Lead')}</h2><span class="pill">${esc(l.status.replaceAll('_',' '))}</span></div><div class="muted">${esc(l.phone)} • ${esc(l.city)}<br>${esc(l.service_requested)}<br>Attempts: ${l.attempt_count}${due?`<br>Due: ${when(l.next_follow_up_at)}`:''}</div><div class="actions"><a class="btn" href="tel:${esc(l.phone)}">Call</a><a class="btn" href="sms:${esc(l.phone)}">Text</a><button class="btn primary" data-log="${l.id}">Log Attempt</button></div></div>`}
function bind(){document.querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>{$('activityId').value=b.dataset.log;$('activityModal').classList.add('show')})}
async function loadLeads(){let{data,error}=await sb.from('leads').select('*').order('received_at',{ascending:false});if(error)return toast(error.message);leads=data||[];$('leadList').innerHTML=leads.length?leads.map(x=>card(x)).join(''):'<div class="card muted">No leads yet.</div>';bind()}
async function loadFollowups(){let{data,error}=await sb.from('leads').select('*').lte('next_follow_up_at',new Date().toISOString()).not('status','in','("approved","lost","do_not_contact","no_response")').order('next_follow_up_at');if(error)return toast(error.message);$('followList').innerHTML=data?.length?data.map(x=>card(x,true)).join(''):'<div class="card muted">No follow-ups due.</div>';bind()}
async function saveLead(){let p={source:'Angi',first_name:$('lfn').value.trim(),last_name:$('lln').value.trim(),phone:$('lphone').value.trim(),email:$('lemail').value.trim(),city:$('lcity').value.trim(),service_requested:$('lservice').value.trim(),original_message:$('lmessage').value.trim(),status:'new',attempt_count:0,next_follow_up_at:new Date().toISOString()};let{error}=await sb.from('leads').insert(p);if(error)return toast(error.message);$('leadModal').classList.remove('show');toast('Lead added to immediate follow-up.');loadLeads()}
function nextDue(n){let d=new Date();if(n===1){d.setHours(18,0,0,0);if(d<new Date())d.setHours(new Date().getHours()+2)}else if(n===2){d.setDate(d.getDate()+1);d.setHours(9,0,0,0)}else if(n===3){d.setDate(d.getDate()+3);d.setHours(9,0,0,0)}else if(n===4){d.setDate(d.getDate()+7);d.setHours(9,0,0,0)}else return null;return d}
async function saveActivity(){let id=$('activityId').value,type=$('activityType').value,note=$('activityNotes').value.trim(),l=leads.find(x=>x.id===id)||(await sb.from('leads').select('*').eq('id',id).single()).data,attempts=l.attempt_count+(['call_no_answer','voicemail','text_sent'].includes(type)?1:0),status=type==='call_no_answer'?'no_answer':type,terminal=['contacted','estimate_scheduled','quote_sent','approved','lost'].includes(status),due=terminal?null:nextDue(attempts);let[a,b]=await Promise.all([sb.from('lead_activities').insert({lead_id:id,activity_type:type,notes:note}),sb.from('leads').update({status,attempt_count:attempts,next_follow_up_at:due?due.toISOString():null,updated_at:new Date().toISOString()}).eq('id',id)]);if(a.error||b.error)return toast((a.error||b.error).message);$('activityModal').classList.remove('show');toast(due?`Next follow-up: ${when(due)}`:'Activity saved.');loadLeads()}
async function openShift(){return (await sb.from('time_entries').select('*,time_breaks(*)').eq('employee_id',session.user.id).eq('status','open').limit(1).maybeSingle()).data}
function renderClock(el,s){if(!s){el.innerHTML=`<div class="clock"><div class="big">${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div><p class="muted">Ready to start</p></div><button class="btn primary wide" id="clockIn">Clock In</button>`;el.querySelector('#clockIn').onclick=clockIn;return}let br=s.time_breaks?.find(x=>!x.break_end);el.innerHTML=`<div class="clock"><div class="big">${br?'On Break':'Clocked In'}</div><p class="muted">Started ${when(s.clock_in)}</p></div><div class="actions">${br?'<button class="btn primary wide" id="endBreak">End Unpaid Break</button>':'<button class="btn" id="startBreak">Start Unpaid Break</button><button class="btn danger" id="clockOut">Clock Out</button>'}</div>`;if(br)el.querySelector('#endBreak').onclick=()=>endBreak(br.id);else{el.querySelector('#startBreak').onclick=()=>startBreak(s.id);el.querySelector('#clockOut').onclick=()=>clockOut(s.id)}}
async function clockIn(){let{error}=await sb.from('time_entries').insert({employee_id:session.user.id});if(error)return toast(error.message);toast('Clocked in.');loadTime();loadEmployee()}
async function clockOut(id){let{error}=await sb.from('time_entries').update({clock_out:new Date().toISOString(),status:'closed'}).eq('id',id);if(error)return toast(error.message);toast('Clocked out.');loadTime();loadEmployee()}
async function startBreak(id){let{error}=await sb.from('time_breaks').insert({time_entry_id:id,unpaid:true});if(error)return toast(error.message);toast('Break started.');loadTime();loadEmployee()}
async function endBreak(id){let{error}=await sb.from('time_breaks').update({break_end:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Break ended.');loadTime();loadEmployee()}
function week(){let d=new Date(),day=d.getDay();d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d.toISOString()}
async function loadTime(){renderClock($('timeCard'),await openShift());let{data}=await sb.from('time_entry_totals').select('*').eq('employee_id',session.user.id).gte('clock_in',week()).order('clock_in',{ascending:false}),tot=(data||[]).reduce((s,x)=>s+Number(x.net_hours||0),0);$('timeList').innerHTML=`<div class="card metric"><b>${tot.toFixed(2)}</b><span>Net hours this week</span></div>`+(data||[]).map(x=>`<div class="item muted">${when(x.clock_in)} → ${when(x.clock_out)}<br>${Number(x.net_hours||0).toFixed(2)} hours</div>`).join('')}
async function loadEmployee(){renderClock($('employeeClock'),await openShift());let{data}=await sb.from('jobs').select('*').eq('assigned_to',session.user.id).order('scheduled_start');$('jobs').innerHTML=data?.length?data.map(j=>`<div class="item"><b>${esc(j.title)}</b><div class="muted">${when(j.scheduled_start)}<br>${esc(j.service_address)}</div></div>`).join(''):'No assigned jobs yet.'}
async function loadTeam(){let{data,error}=await sb.from('time_entry_totals').select('*,profiles(full_name,email)').gte('clock_in',week()).order('clock_in',{ascending:false});if(error)return toast(error.message);$('teamList').innerHTML=data?.length?data.map(x=>`<div class="item"><b>${esc(x.profiles?.full_name||x.profiles?.email)}</b><div class="muted">${when(x.clock_in)} → ${when(x.clock_out)}<br>${Number(x.net_hours||0).toFixed(2)} hours</div></div>`).join(''):'<div class="card muted">No time entries this week.</div>'}
$('login').onclick=login;$('reset').onclick=reset;$('logout').onclick=()=>sb.auth.signOut();$('addLead').onclick=()=>$('leadModal').classList.add('show');$('saveLead').onclick=saveLead;$('saveActivity').onclick=saveActivity;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('show'));sb.auth.onAuthStateChange(async(_,s)=>{session=s;if(s){try{await enter()}catch(e){$('message').textContent=e.message}}else{$('app').classList.add('hidden');$('auth').classList.remove('hidden')}});session=(await sb.auth.getSession()).data.session;if(session)await enter();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');